name: Check PR Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt
          else
            # fallback for CI if requirements.txt is missing
            python -m pip install requests "PyJWT[crypto]"
          fi

      # Step 4: Verify installation
      - name: Verify installed packages
        run: |
          python -m pip list
          python -c "import requests, jwt; print('✅ requests:', requests.__version__, '| ✅ PyJWT:', jwt.__version__)"
      
      # Step 5: Run your branch check script
      - name: Run branch check
        run: python .github/workflows/scripts/check_branch.py
        env:
          TARGET_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DATAGREMLIN_APP_KEY: ${{ secrets.DATAGREMLIN_APP_KEY }}
          DATAGREMLIN_APP_ID: ${{ secrets.DATAGREMLIN_APP_ID }}
