name: Check PR Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Always install requests
          python -m pip install requests
          # Install any other dependencies from requirements.txt if it exists
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping."
          fi

      # Step 4: Verify installed packages (optional)
      - name: Verify installed packages
        run: python -m pip list

      # Step 5: Run your branch check script
      - name: Run branch check
        run: python .github/workflows/scripts/check_branch.py
        env:
          TARGET_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DATAGREMLIN_APP_KEY: ${{ secrets.DATAGREMLIN_APP_KEY }}
          DATAGREMLIN_APP_ID: ${{ secrets.DATAGREMLIN_APP_ID }}
