name: PR Branch Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies from requirements.txt
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip -r .github/workflows/requirements.txt

      # Step 4: Run branch check script
      - name: Run branch check
        env:
          TARGET_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DATAGREMLIN_APP_KEY: ${{ secrets.DATAGREMLIN_APP_KEY }}
          DATAGREMLIN_APP_ID: ${{ secrets.DATAGREMLIN_APP_ID }}
        run: python .github/workflows/scripts/check_branch.py
