name: PR Branch Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests PyJWT

      # Step 4: Verify installed packages
      - name: Verify installed packages
        run: |
          python -m pip list
          python -c "import requests; print('requests installed')"
          python -c "import jwt; print('PyJWT installed')"

      # Step 5: Run branch check script
      - name: Run branch check
        env:
          TARGET_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DATAGREMLIN_APP_KEY: ${{ secrets.DATAGREMLIN_APP_KEY }}
          DATAGREMLIN_APP_ID: ${{ secrets.DATAGREMLIN_APP_ID }}
        run: python .github/workflows/scripts/check_branch.py
